<?php
/**
 * VietNam Province/City
 *
 * @package FriendStore for WooCommerce
 * @version 1.0.0
 */

$cities = array(
    ""   => __('Select Province/City', 'friendstore-for-woocommerce'),
    "202" => __('Hồ Chí Minh city', 'friendstore-for-woocommerce'),
    "201" => __('Hà Nội city', 'friendstore-for-woocommerce'),
    "217" => __('An Giang province', 'friendstore-for-woocommerce'),
    "219" => __('Kiên Giang province', 'friendstore-for-woocommerce'),
    "209" => __('Lâm Đồng province', 'friendstore-for-woocommerce'),
    "231" => __('Nam Định province', 'friendstore-for-woocommerce'),
    "235" => __('Nghệ An province', 'friendstore-for-woocommerce'),
    "260" => __('Phú Yên province', 'friendstore-for-woocommerce'),
    "237" => __('Quảng Bình province', 'friendstore-for-woocommerce'),
    "238" => __('Quảng Trị province', 'friendstore-for-woocommerce'),
    "240" => __('Tây Ninh province', 'friendstore-for-woocommerce'),
    "234" => __('Thanh Hóa province', 'friendstore-for-woocommerce'),
    "223" => __('Thừa Thiên - Huế province', 'friendstore-for-woocommerce'),
    "248" => __('Bắc Giang province', 'friendstore-for-woocommerce'),
    "249" => __('Bắc Ninh province', 'friendstore-for-woocommerce'),
    "262" => __('Bình Định province', 'friendstore-for-woocommerce'),
    "239" => __('Bình Phước province', 'friendstore-for-woocommerce'),
    "258" => __('Bình Thuận province', 'friendstore-for-woocommerce'),
    "252" => __('Cà Mau province', 'friendstore-for-woocommerce'),
    "210" => __('Đắk Lắk province', 'friendstore-for-woocommerce'),
    "241" => __('Đắk Nông province', 'friendstore-for-woocommerce'),
    "207" => __('Gia Lai province', 'friendstore-for-woocommerce'),
    "232" => __('Hà Nam province', 'friendstore-for-woocommerce'),
    "236" => __('Hà Tĩnh province', 'friendstore-for-woocommerce'),
    "225" => __('Hải Dương province', 'friendstore-for-woocommerce'),
    "250" => __('Hậu Giang province', 'friendstore-for-woocommerce'),
    "268" => __('Hưng Yên province', 'friendstore-for-woocommerce'),
    "208" => __('Khánh Hòa province', 'friendstore-for-woocommerce'),
    "204" => __('Đồng Nai province', 'friendstore-for-woocommerce'),
    "205" => __('Bình Dương province', 'friendstore-for-woocommerce'),
    "206" => __('Bà Rịa - Vũng Tàu province', 'friendstore-for-woocommerce'),
    "211" => __('Long An province', 'friendstore-for-woocommerce'),
    "203" => __('Đà Nẵng city', 'friendstore-for-woocommerce'),
    "212" => __('Tiền Giang province', 'friendstore-for-woocommerce'),
    "213" => __('Bến Tre province', 'friendstore-for-woocommerce'),
    "214" => __('Trà Vinh province', 'friendstore-for-woocommerce'),
    "215" => __('Vĩnh Long province', 'friendstore-for-woocommerce'),
    "216" => __('Đồng Tháp province', 'friendstore-for-woocommerce'),
    "218" => __('Sóc Trăng province', 'friendstore-for-woocommerce'),
    "220" => __('Cần Thơ city', 'friendstore-for-woocommerce'),
    "221" => __('Vĩnh Phúc province', 'friendstore-for-woocommerce'),
    "224" => __('Hải Phòng city', 'friendstore-for-woocommerce'),
    "242" => __('Quảng Ngãi province', 'friendstore-for-woocommerce'),
    "243" => __('Quảng Nam province', 'friendstore-for-woocommerce'),
    "245" => __('Bắc Kạn province', 'friendstore-for-woocommerce'),
    "246" => __('Cao Bằng province', 'friendstore-for-woocommerce'),
    "247" => __('Lạng Sơn province', 'friendstore-for-woocommerce'),
    "263" => __('Yên Bái province', 'friendstore-for-woocommerce'),
    "267" => __('Hòa Bình province', 'friendstore-for-woocommerce'),
    "230" => __('Quảng Ninh province', 'friendstore-for-woocommerce'),
    "233" => __('Ninh Bình province', 'friendstore-for-woocommerce'),
    "226" => __('Thái Bình province', 'friendstore-for-woocommerce'),
    "227" => __('Hà Giang province', 'friendstore-for-woocommerce'),
    "228" => __('Tuyên Quang province', 'friendstore-for-woocommerce'),
    "229" => __('Phú Thọ province', 'friendstore-for-woocommerce'),
    "264" => __('Lai Châu province', 'friendstore-for-woocommerce'),
    "265" => __('Điện Biên province', 'friendstore-for-woocommerce'),
    "266" => __('Sơn La province', 'friendstore-for-woocommerce'),
    "259" => __('Kon Tum province', 'friendstore-for-woocommerce'),
    "261" => __('Ninh Thuận province', 'friendstore-for-woocommerce'),
    "269" => __('Lào Cai province', 'friendstore-for-woocommerce'),
    "244" => __('Thái Nguyên province', 'friendstore-for-woocommerce'),
    "253" => __('Bạc Liêu province', 'friendstore-for-woocommerce'),
);